/*
Package include imports all input packages so that they register
their factories with the global registry. This package can be imported in the
main package to automatically register all of the standard supported inputs
modules.
*/
package include

import (
	// This list is automatically generated by `make imports`
	_ "github.com/sequra/s3logsbeat/input/s3"
	_ "github.com/sequra/s3logsbeat/input/sqs"
)
